# Generated by Django 5.2.5 on 2025-09-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_followup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='satus',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='followup',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
