# Generated by Django 5.2.7 on 2025-11-18 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_rename_satus_lead_status_alter_followup_remarks'),
        ('users', '0002_alter_userrole_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='users.userrole'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('google', 'Google Ads'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('website', 'Website'), ('referral', 'Referral'), ('linkedin', 'LinkedIn'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='followup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_followups', to='users.userrole'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='next_followup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followups', to='users.userrole'),
        ),
    ]
